# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Render Deployment

on:
  push:
    branches:
      - CI/CD # Define the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify the Node.js version
          cache: "yarn" # Cache Yarn packages to speed up workflows

      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile  # Use Yarn to install dependencies
          yarn build  # Modify build script as needed

      - name: Deploy to Render
        run: |
          render deploy -- --local --file render.yaml  # Adjust render command as per your Render setup
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
